title: Kavin M. Govindarajan # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <h2>About Me:</h2>
  Aerospace Engineering and Applied Mathematics Student at NCSU interested in Space, Robotics, and Autonomous Controls/Optimization.
  <br>
  Park Scholar at North Carolina State University
  <br><br>
  <h2>Degrees:</h2>
  BS Aerospace Engineering
  <br>
  BS Applied Mathematics
  <br><br>
  <a href="pdf/Kavin_Govindarajan_Resume.pdf" target="_blank">View My Resume</a>
  <br>
  <a href="https://www.linkedin.com/in/kmgovind/" target="_blank">View My LinkedIn Profile</a> 
  <br>
  <a href="https://www.github.com/kmgovind/" target="_blank">View My Github Profile</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
